### ISSUE TITLE
How can I use it with Gulp?

### ISSUE THREAD

**Issue by alebak** [vidavidorra/next-standard-version#228]
# 💬 Question

Hello,

How can I use it in a Gulp task?

**Comment by jdbruijn** [comment]
I don't know, I've never used Gulp. In any regard you would need to install it and can call it either via the CLI or the API, as documented in the readme. So if Gulp can be used to run some JS/TS code, you should be able to import this package and use [the API](https://github.com/vidavidorra/next-standard-version#api).

Not sure how I can help you more. I have no experience with Gulp and how it works/what it can do.

**Comment by jdbruijn** [comment]
Looks like you can just create tasks as a function. That would allow you to use the API as I've described above. This is just after a quick look at the Gulp docs, so might be missing something 😉 

https://gulpjs.com/docs/en/getting-started/creating-tasks

**Comment by alebak** [comment]
Hi @jdbruijn,

Thanks for getting back to me, I was able to make it work!

JS:

```js
var { nextStandardVersion } = require("next-standard-version");

nextStandardVersion({
    modulePath: "./node_modules/standard-version",
}) .then((version) => {
    console.log(version);
}).catch((error) => {
    console.error(error);
});
```

Best regards.
